// ── The rules that keep this from turning into a listicle ────────────────────
// 1. Every town gets a "watch out". If you can't name what's wrong, you haven't researched it.
// 2. Never fake a number. No clean median → verified: false, and the app says so.
// 3. The timing tag (early / heating / late) is the product.
// 4. No crime stats — reputable sources reach opposite conclusions from the same FBI data.
// 5. No demographic targeting.

export const US = {
  AL: "Alabama", AK: "Alaska", AZ: "Arizona", AR: "Arkansas", CA: "California",
  CO: "Colorado", CT: "Connecticut", DE: "Delaware", FL: "Florida", GA: "Georgia",
  HI: "Hawaii", ID: "Idaho", IL: "Illinois", IN: "Indiana", IA: "Iowa",
  KS: "Kansas", KY: "Kentucky", LA: "Louisiana", ME: "Maine", MD: "Maryland",
  MA: "Massachusetts", MI: "Michigan", MN: "Minnesota", MS: "Mississippi", MO: "Missouri",
  MT: "Montana", NE: "Nebraska", NV: "Nevada", NH: "New Hampshire", NJ: "New Jersey",
  NM: "New Mexico", NY: "New York", NC: "North Carolina", ND: "North Dakota", OH: "Ohio",
  OK: "Oklahoma", OR: "Oregon", PA: "Pennsylvania", RI: "Rhode Island", SC: "South Carolina",
  SD: "South Dakota", TN: "Tennessee", TX: "Texas", UT: "Utah", VT: "Vermont",
  VA: "Virginia", WA: "Washington", WV: "West Virginia", WI: "Wisconsin", WY: "Wyoming",
};

// Hand-researched states. Anything not in here gets researched live by /api/research
// and can be promoted into this file once you've checked it.
export const STATES = {
  FL: {
    name: "Florida",
    blurb:
      "Small town, near a beach, near Disney, $400k. The catch: on this budget you can be twenty minutes from Disney or twenty minutes from sand. Not both.",
    criteria: [
      { id: "disney", label: "Close to Disney" },
      { id: "beach", label: "Close to a beach" },
      { id: "small", label: "Small-town feel" },
      { id: "jobs", label: "Job market" },
      { id: "risk", label: "Low storm & insurance risk" },
    ],
    footer: [
      "The state median is around $395k–$425k and roughly flat. Homes take about 84 days to sell and inventory is the highest since the boom. That's a buyer's market.",
      "What decides your payment isn't the price, it's insurance — averaging about $8,460 a year statewide, nearer $5,500 inland in Polk and $11,000+ on the coast. Quote the exact address before you get attached.",
      "Condo reserve rules that took full effect in January 2026 are triggering five-figure special assessments in older buildings. Read the association's finances before you buy one.",
    ],
    towns: [
      {
        id: "titusville", name: "Titusville", sub: "Brevard County · pop. ~50,000",
        z: "titusville-fl", r: "Titusville_FL", stage: "early", verified: true,
        price: 272000, priceLabel: "$272k", delta: "−3.4% this year",
        scores: { disney: 2, beach: 5, small: 4, jobs: 4, risk: 2 },
        hook: "America's second space boom is happening here and the housing market hasn't noticed.",
        never: "When the Shuttle ended in 2011, Titusville lost thousands of jobs almost overnight and dropped off every list it was ever on. It never got added back.",
        history: "Built on citrus and the Indian River, then remade in the 1960s when NASA arrived across the water. It emptied out after the Shuttle and spent a decade cheap and quiet.",
        why: [
          "The cheapest coastal buy in Central Florida by a wide margin",
          "Private space is refilling the jobs the Shuttle took: SpaceX, Blue Origin, Amazon's Kuiper",
          "Canaveral National Seashore is fifteen minutes east — undeveloped beach, no high-rises",
        ],
        jobs: "Aerospace and defense: Blue Origin, SpaceX, Amazon Kuiper, L3Harris, Lockheed — plus everything that feeds a launch site.",
        get: "A three-bed under $275k, fifteen minutes from a beach with no buildings on it.",
        cost: "Coastal Brevard. Budget high for insurance — the Florida average is about $8,460/yr.",
        doing: [
          "Playalinda Beach — wild, unbuilt, part of the National Seashore",
          "Kennedy Space Center Visitor Complex, ten minutes away",
          "Merritt Island National Wildlife Refuge — manatees, roseate spoonbills",
          "Downtown's riverfront: the best free seats in the country for a launch",
        ],
        watch: [
          "The market is soft — homes sat around 184 days earlier this year, and prices are down",
          "Real flood and wind exposure. Quote the address before you fall in love",
          "It's an hour to Disney, not twenty minutes",
        ],
        sources: ["Zillow", "Houzeo", "HouseCanary"],
      },
      {
        id: "deland", name: "DeLand", sub: "Volusia County · pop. ~38,000",
        z: "deland-fl", r: "Deland_FL", stage: "early", verified: true,
        price: 333000, priceLabel: "$333k", delta: "+2.1% this year",
        scores: { disney: 3, beach: 3, small: 5, jobs: 3, risk: 4 },
        hook: "The best small-town downtown in Central Florida, and the only one here still appreciating.",
        never: "It sits inland, between the beach towns and the theme parks, so tourists drive past it in both directions and nobody stops.",
        history: "Founded in the 1880s by a baking-soda magnate who wanted an 'Athens of Florida', and he mostly got one. Stetson University has anchored it since 1883, and the brick downtown survived the decades when the rest of Florida bulldozed everything.",
        why: [
          "One of the only towns here where prices are still climbing, not sliding",
          "A genuine walkable main street — not a master-planned imitation of one",
          "Sits in the gap: under an hour to Disney, forty minutes to New Smyrna Beach",
        ],
        jobs: "Stetson University and AdventHealth are the steady employers. Thin for anything specialised — this is a remote-work town.",
        get: "A house at $333k in the one Central Florida town with a real main street.",
        cost: "Inland Volusia — cheaper insurance than the coast, dearer than Polk.",
        doing: [
          "Woodland Boulevard — the brick street, the Athens Theatre",
          "Blue Spring State Park — manatees by the hundred in winter",
          "De Leon Springs, where you cook your own pancakes at the table",
          "New Smyrna Beach, forty minutes east",
        ],
        watch: [
          "Every property here carries extreme wind risk. That's Florida, but price it in",
          "The job market is shallow if you ever stop working remote",
          "You're not close to a beach — you're a drive from one",
        ],
        sources: ["Zillow", "Redfin", "Movoto"],
      },
      {
        id: "davenport", name: "Davenport", sub: "Polk County · pop. ~10,000",
        z: "davenport-fl", r: "Davenport_FL", stage: "heating", verified: false,
        price: 400000, priceLabel: "~$400k", delta: "Builder-driven market",
        scores: { disney: 5, beach: 1, small: 3, jobs: 2, risk: 4 },
        hook: "Closest to the parks your money can get you — and the cheapest insurance in the region.",
        never: "It reads as an exit off Highway 27 — a strip of new subdivisions people assume are all vacation rentals.",
        history: "A citrus and cattle waypoint that Disney's gravity turned into a subdivision belt. Almost everything you'll tour was built after 2015.",
        why: [
          "Fifteen to twenty minutes to Disney. Nothing else at this price is that close",
          "Inland Polk has the cheapest insurance in the region, which is worth more than it sounds",
          "Builder incentives and rate buy-downs are thick on the ground right now",
        ],
        jobs: "Tourism, hospitality, healthcare, logistics along I-4. Real careers are in Orlando, forty minutes up the road.",
        get: "A pool home from the low $400ks, eighteen minutes from Magic Kingdom.",
        cost: "Inland Polk — premiums nearer $5,500/yr than the $11,000 you'd see on the coast.",
        doing: [
          "Disney. You'd be an annual passholder within a month",
          "Posner Park for everything chain-store and multiplex",
          "ChampionsGate golf",
          "Bok Tower Gardens in Lake Wales — the one genuinely strange, beautiful thing nearby",
        ],
        watch: [
          "No beach. Ninety minutes to either coast, and that drive gets old fast",
          "Heavy short-term-rental presence — some streets are more Airbnb than neighbours",
          "You're buying proximity, not a place",
        ],
        sources: ["ez Home Search", "GoBankingRates"],
      },
      {
        id: "palmbay", name: "Palm Bay", sub: "Brevard County · pop. ~152,000",
        z: "palm-bay-fl", r: "Palm-Bay_FL", stage: "late", verified: true,
        price: 315000, priceLabel: "$315k", delta: "−3.1%, listings up 73%",
        scores: { disney: 1, beach: 5, small: 2, jobs: 3, risk: 2 },
        hook: "Cheap, coastal, and falling. Buyers have leverage — and possibly a falling knife.",
        never: "It has 152,000 people and no downtown. A city that big with no centre doesn't register as a place, so nobody talks about it.",
        history: "Platted in the 1960s as a lot-sale scheme — thousands of acres of gridded streets sold sight-unseen to northerners. It's been filling in that grid ever since.",
        why: [
          "One of the cheapest ways in Florida to live twenty minutes from the Atlantic",
          "Growing at 3.7% a year, now past 152,000 people",
          "Inventory nearly doubled and homes average one offer — you can negotiate hard",
        ],
        jobs: "L3Harris is the anchor. Space Coast aerospace and defense spills down from Melbourne.",
        get: "$315k for twenty minutes from the Atlantic — if you can stomach a market that's still sliding.",
        cost: "Coastal Brevard — high insurance, and the main reason locals are listing.",
        doing: [
          "Turkey Creek Sanctuary — boardwalks and manatees in the middle of town",
          "Melbourne Beach and Indialantic, twenty minutes east",
          "Sebastian Inlet — fishing, and the best surf on this coast",
          "The Avenue Viera for shops and dinner",
        ],
        watch: [
          "Prices are falling and one analysis still calls homes ~10% overvalued",
          "It's a sprawling grid, not a small town, whatever the map suggests",
          "Nearly ninety minutes to Disney",
        ],
        sources: ["Redfin", "The Palm Bayer", "HouseCanary"],
      },
    ],
  },

  NV: {
    name: "Nevada",
    blurb:
      "None of these is Vegas or Reno. In Florida the hidden cost is insurance. Here it's water — and it never appears on a listing.",
    criteria: [
      { id: "jobs", label: "Job market" },
      { id: "small", label: "Small-town feel" },
      { id: "city", label: "Near a real city" },
      { id: "water", label: "Water security" },
      { id: "heat", label: "Bearable summers" },
    ],
    footer: [
      "No state income tax. Property tax runs 0.50%–0.70% of assessed value, and the annual increase on a primary residence is capped at 3%. That cap compounds into real money.",
      "Home insurance is cheap — roughly $1,500–$2,500 a year — but it does not cover drought loss or well failure. In a state running out of groundwater, read that twice.",
      "Aquifer restrictions are already in force in Pahrump and Lyon County. If a house is on a well rather than municipal water, the water right is the asset. Have someone check it before you sign.",
    ],
    towns: [
      {
        id: "elko", name: "Elko", sub: "Elko County · pop. ~20,000",
        z: "elko-nv", r: "Elko_NV", stage: "early", verified: true,
        price: 350000, priceLabel: "$350k", delta: "+1.6% this year",
        scores: { jobs: 5, small: 4, city: 1, water: 3, heat: 4 },
        hook: "Gold is near record highs, and the town that digs it out has the best job market in the state.",
        never: "It's four and a half hours from Reno on I-80, surrounded by nothing, and it has never once appeared on a 'best places to live' list. Basque sheepherders settled it. Miners kept it.",
        history: "A Central Pacific railroad stop that became the capital of the Carlin Trend — one of the richest gold districts on earth. When gold is up, Elko is up. Gold is up.",
        why: [
          "Cost of living runs about 5% under the state average, with wages that don't",
          "Nevada Gold Mines is the largest gold-producing complex in the world, and it's next door",
          "The Ruby Mountains are the best hiking in Nevada and almost nobody goes",
        ],
        jobs: "Mining and everything that serves it — Nevada Gold Mines, Freeport, plus contractors, assayers and heavy-equipment shops. Six-figure trade jobs are normal here.",
        get: "A house around $350k, a real job market, and the Ruby Mountains out the back window.",
        cost: "Insurance is cheap. Distance is the tax you pay.",
        watch: [
          "You are genuinely remote. Specialist medicine means flying",
          "The whole economy is one commodity price. When gold turns, Elko turns",
          "Winters are cold and long — this isn't the Nevada people picture",
        ],
        sources: ["Zillow", "Houzeo"],
      },
      {
        id: "yerington", name: "Yerington", sub: "Lyon County · pop. ~3,500",
        z: "yerington-nv", r: "Yerington_NV", stage: "early", verified: false,
        price: 250000, priceLabel: "Check listings", delta: "No clean median",
        scores: { jobs: 1, small: 5, city: 3, water: 3, heat: 2 },
        hook: "An onion-farming town an hour from Reno that the Tesla corridor hasn't reached yet — but is heading toward.",
        never: "There is no reason to drive through Yerington. That's the whole point of it.",
        history: "Copper and agriculture in the Mason Valley. The Anaconda mine defined the town, then closed and left a Superfund site behind. It's been quietly farming ever since.",
        why: [
          "The industrial build-out along the Reno–Fernley corridor keeps creeping east",
          "The cheapest doorway into western Nevada, where everything else has already run",
          "Actual farmland and actual quiet, an hour from a real airport",
        ],
        jobs: "Thin. Seasonal agriculture and little else. Unemployment runs around 7%, above the state average — people commute to Fernley or Carson.",
        get: "Land and silence, cheap. Verify any price yourself — this market is too small for reliable medians.",
        cost: "Cheap to buy, expensive to be far from things.",
        watch: [
          "Almost no local employment. If you're not remote or retired, this doesn't work",
          "You drive to Fernley for anything beyond a grocery run",
          "Legacy mine contamination is part of this town's story — do your diligence on the site",
        ],
        sources: ["Houzeo", "Niche"],
      },
      {
        id: "fernley", name: "Fernley", sub: "Lyon County · pop. ~24,000",
        z: "fernley-nv", r: "Fernley_NV", stage: "heating", verified: true,
        price: 394000, priceLabel: "$394k", delta: "Up 319% since 2012",
        scores: { jobs: 4, small: 3, city: 5, water: 2, heat: 3 },
        hook: "Nevada's third-fastest-growing city, and where Reno's industrial boom actually lands.",
        never: "It was a railroad siding with a truck stop. Most Nevadans still think of it that way.",
        history: "A quiet rail town on I-80 that became the release valve for Reno — then found itself next to the Tahoe-Reno Industrial Center, the largest industrial park in the world, with Tesla's Gigafactory in it.",
        why: [
          "Growing 2.38% a year, third-fastest in the state",
          "Rare for an exurb: actual local jobs in distribution and manufacturing, not just a commute",
          "Still meaningfully cheaper than Reno — though the gap is closing",
        ],
        jobs: "Logistics and manufacturing. Amazon, Walmart distribution, and the TRIC industrial park up the road — Tesla, Panasonic, Google.",
        get: "A newer house under $400k, thirty minutes from Reno, with work you can drive to in ten.",
        cost: "Water is the constraint, not insurance. Aquifer restrictions are already biting in Lyon County.",
        watch: [
          "Values are up 319% since 2012. You are not early here",
          "Water rights are the live issue — check them on any property",
          "The wind and dust are genuinely relentless",
        ],
        sources: ["Zillow", "World Population Review"],
      },
      {
        id: "mesquite", name: "Mesquite", sub: "Clark County · pop. ~24,000",
        z: "mesquite-nv", r: "Mesquite_NV", stage: "heating", verified: true,
        price: 374400, priceLabel: "$374k", delta: "Fastest-growing city in Nevada",
        scores: { jobs: 2, small: 4, city: 2, water: 2, heat: 1 },
        hook: "Growing 2.97% a year — faster than anywhere else in the state — and it's a golf town on the Arizona line.",
        never: "It's eighty miles past the point where most people stop paying attention to I-15.",
        history: "A Mormon farming settlement on the Virgin River that discovered, in the 1980s, that it was allowed to have casinos and Arizona wasn't. Golf courses and retirees followed.",
        why: [
          "The fastest-growing city in Nevada, at 2.97% annualised",
          "No state income tax, low property tax, and a real hospital — the retiree math works",
          "Zion and the Virgin River gorge are on the doorstep",
        ],
        jobs: "Casinos, healthcare, construction and services for retirees. If you need a career rather than a job, this is a hard place to build one.",
        get: "A newer home around $374k in the fastest-growing city in the state, with golf you can walk to.",
        cost: "Colorado River water politics hang over this entire corner of the state.",
        watch: [
          "The heat is extreme even by Nevada standards",
          "It skews heavily retired — thin on schools, thinner on things for teenagers",
          "Long-term water supply is a genuine open question here",
        ],
        sources: ["NewHomeSource", "World Population Review", "Niche"],
      },
      {
        id: "pahrump", name: "Pahrump", sub: "Nye County · pop. ~47,000",
        z: "pahrump-nv", r: "Pahrump_NV", stage: "late", verified: true,
        price: 372000, priceLabel: "$372k", delta: "Up 200%+ since 2012",
        scores: { jobs: 1, small: 3, city: 3, water: 1, heat: 1 },
        hook: "The Vegas escape hatch. Big lots, no income tax, and a groundwater problem nobody wants to discuss.",
        never: "An hour of desert past the last suburb, in a valley you'd only find on purpose.",
        history: "A ranching valley that filled with people who wanted to be left alone — sixty miles from the Strip and one mountain range from California.",
        why: [
          "Cost of living about 19% below the state average — the cheapest in Nevada",
          "Acreage, horses, and space you cannot buy anywhere near Las Vegas",
          "Retirees and remote workers keep arriving; the population is now 47,000",
        ],
        jobs: "Hourly casino and retail work. Professionals commute the sixty miles to Vegas, or don't work locally at all.",
        get: "A big lot and a $372k house — but values have already tripled since 2012.",
        cost: "Standard insurance does not cover well failure or drought loss. Aquifer restrictions are in force.",
        watch: [
          "Water. This is the defining risk and it is not priced into the listings",
          "Healthcare is a 60-mile drive for anything serious",
          "The dust and wind are constant, and the summer heat is brutal",
        ],
        sources: ["Zillow", "Houzeo"],
      },
    ],
  },

  MT: {
    name: "Montana",
    blurb:
      "The state has split in two. Bozeman is at $1.13M and Whitefish is worse, while a hundred miles east the same house is $230k. Every find lives in that gap.",
    criteria: [
      { id: "jobs", label: "Job market" },
      { id: "small", label: "Small-town feel" },
      { id: "airport", label: "Near an airport" },
      { id: "winter", label: "Survivable winters" },
      { id: "fire", label: "Low wildfire risk" },
    ],
    footer: [
      "The state median is $505,000. Everything here is below it — that's the point, but it also tells you where the pressure is coming from.",
      "Montana has a state income tax. Nevada and Florida don't. If you're comparing across these boards, that's real money every year.",
      "Property tax is the live political fight — reappraisals have moved bills sharply. Havre's median bill is about $2,065; Billings runs nearer $3,942. Ask for the bill on the actual house, not the county average.",
      "Wildfire smoke is the cost nobody quotes. It shuts down weeks of summer in bad years, it affects insurance, and it's worse in the western valleys than out on the plains.",
    ],
    towns: [
      {
        id: "milescity", name: "Miles City", sub: "Custer County · pop. ~8,400",
        z: "miles-city-mt", r: "Miles-City_MT", stage: "early", verified: true,
        price: 180000, priceLabel: "$180k", delta: "Cheapest on any board",
        scores: { jobs: 2, small: 5, airport: 1, winter: 1, fire: 4 },
        hook: "A working cowboy town where a renovated four-bedroom Victorian lists for under $200k.",
        never: "It's on the eastern plains, three hours from anywhere you've heard of, and it has never tried to be discovered.",
        history: "A Yellowstone River garrison town that became the cattle capital of eastern Montana. The Bucking Horse Sale still runs every May, and it is not a re-enactment.",
        why: [
          "The median is around $180,000 — a house that would fetch $800k in Bozeman",
          "It has a community college and a regional hospital, which most towns this size don't",
          "Median household income is about $60,700 against that price. The ratio is the point",
        ],
        jobs: "Healthcare, agriculture, rail and the community college. Not a career market — a cost-of-living arbitrage for people who bring their own work.",
        get: "A restored Victorian, outright, for the price of a Bozeman down payment.",
        cost: "Among the lowest property tax bills in the state.",
        watch: [
          "145 miles from a commercial airport, and 200+ from real specialist medicine",
          "Winters on the plains are the serious kind. This is the trade",
          "If you need a well-paid local job, this doesn't work",
        ],
        sources: ["Roaming Montana", "US Cost of Living"],
      },
      {
        id: "havre", name: "Havre", sub: "Hill County · pop. ~10,000",
        z: "havre-mt", r: "Havre_MT", stage: "early", verified: true,
        price: 232000, priceLabel: "$232k", delta: "Cheapest place to live in Montana",
        scores: { jobs: 3, small: 5, airport: 2, winter: 1, fire: 4 },
        hook: "The most affordable town in Montana — and it has a university, a hospital and a railroad.",
        never: "It's on the Hi-Line, forty miles from Canada, on the highway nobody drives unless they live there.",
        history: "A Great Northern Railway division point named — probably — by French-Canadian settlers. The trains never stopped running, which is why the town never died.",
        why: [
          "Affordability ratio of 4.5 — a $232k median against a $51,900 median income",
          "The lowest property tax bill in Montana, around $2,065 a year",
          "Beaver Creek Park, one of the largest county parks in the country, on the doorstep",
        ],
        jobs: "Three real anchors for a town this size: Montana State University–Northern, Northern Montana Health Care, and BNSF Railway.",
        get: "A three-bedroom well under $250k, in a town with a university and a hospital.",
        cost: "Median property tax about $2,065 — the lowest in the state.",
        watch: [
          "The nearest real airport is two hours away in Great Falls. Billings is four",
          "Hi-Line winters are long, dark and genuinely hard. Don't romanticise this",
          "The economy is stable, not growing — you're buying cheapness, not upside",
        ],
        sources: ["Clever", "Houzeo", "Bozeman Real Estate Group"],
      },
      {
        id: "butte", name: "Butte", sub: "Silver Bow County · pop. ~35,000",
        z: "butte-mt", r: "Butte_MT", stage: "heating", verified: true,
        price: 276000, priceLabel: "$276k", delta: "+2.2% forecast",
        scores: { jobs: 3, small: 3, airport: 3, winter: 2, fire: 3 },
        hook: "Ninety miles from Bozeman, at a quarter of the price. The best arbitrage in Montana.",
        never: "Everyone's heard of Butte. Nobody thinks of it as somewhere to move — they think of it as somewhere that used to matter.",
        history: "The Richest Hill on Earth: a copper city that built the electrification of America, drew a hundred thousand people, then collapsed when the mines closed and left the Berkeley Pit behind. It has the best Victorian architecture in the state because nobody could afford to knock it down.",
        why: [
          "A $276k median while Bozeman, ninety miles up I-90, runs north of $1.1M",
          "Montana Tech is a genuinely good engineering school and it anchors the town",
          "Uptown Butte is a walkable, dense, extraordinary piece of preserved architecture",
        ],
        jobs: "Montana Tech, healthcare, and the mining and engineering firms that never quite left. Bozeman is commutable if you're willing to drive it.",
        get: "A Victorian in Uptown for what a studio costs in Bozeman.",
        cost: "Median property tax about $2,518.",
        watch: [
          "The Berkeley Pit is a Superfund site and it is right there. Look into it properly",
          "Air quality can be poor — wildfire smoke in summer, inversions in winter",
          "Bozeman money is starting to notice. That's why it's here and not one bracket up",
        ],
        sources: ["Clever", "Bozeman Real Estate Group", "Houzeo"],
      },
      {
        id: "greatfalls", name: "Great Falls", sub: "Cascade County · pop. ~60,000",
        z: "great-falls-mt", r: "Great-Falls_MT", stage: "heating", verified: true,
        price: 284000, priceLabel: "$284k", delta: "Metro values up ~6%",
        scores: { jobs: 4, small: 2, airport: 5, winter: 2, fire: 3 },
        hook: "A real city with an air force base, an airport, and a cost of living 22% under the national average.",
        never: "It's the city Montanans drive through. The mountains are elsewhere, so the money went elsewhere.",
        history: "Built where the Missouri drops 500 feet in a series of falls — the portage that nearly broke Lewis and Clark. Hydropower made it an industrial city, and Malmstrom Air Force Base has kept it one.",
        why: [
          "Cost of living around 91% of the national average, with a median income near $63,900",
          "Malmstrom AFB is a permanent, federally-funded floor under the whole city",
          "An actual airport, actual hospitals, actual jobs — at $284k",
        ],
        jobs: "Malmstrom Air Force Base, Benefis Health System, energy and agriculture. The deepest job market on any of these boards outside Elko.",
        get: "A solid family house under $300k in a city with a hospital, an airport and a base payroll.",
        cost: "Middle of the pack for Montana property tax.",
        watch: [
          "It's flat and windy, and it isn't the postcard Montana — the mountains are a drive away",
          "Growth is steady rather than exciting. This is stability, not upside",
          "Wildfire smoke settles here in bad summers",
        ],
        sources: ["Clever", "SoFi", "US Cost of Living"],
      },
      {
        id: "kalispell", name: "Kalispell", sub: "Flathead County · pop. ~30,000",
        z: "kalispell-mt", r: "Kalispell_MT", stage: "late", verified: true,
        price: 727594, priceLabel: "$728k", delta: "+4.0% and still climbing",
        scores: { jobs: 3, small: 3, airport: 5, winter: 3, fire: 1 },
        hook: "Glacier's gateway town, now at $728k. In here as the mirror — this is what 'found' looks like.",
        never: "You have heard of it. That's exactly why it's on the board.",
        history: "A Flathead Valley railroad town that spent a century as a timber and farming hub, then discovered that being twenty minutes from Glacier National Park was worth more than lumber.",
        why: [
          "Glacier National Park, Flathead Lake and Whitefish Mountain are all right there",
          "Real hospital, real airport, real town — not a resort husk",
          "Values keep climbing, so the people who bought early were right",
        ],
        jobs: "Healthcare, tourism, construction and a surprising amount of aerospace manufacturing. Wages have not kept pace with housing, and locals will tell you so.",
        get: "Not much. $728k is the typical home, and the gap to local wages is why service jobs here go unfilled.",
        cost: "Flathead taxes have climbed with the values. Wildfire drives the insurance.",
        watch: [
          "This is the top of the market, not the bottom. Up 4% again this year",
          "Wildfire and smoke are the real risk in the Flathead — check insurance first",
          "The town is in an open fight about what the growth has done to it",
        ],
        sources: ["Zillow", "Stacker"],
      },
    ],
  },
};

// Towns with no state board of their own — they only show up in "Never heard of it"
export const FINDS = [
  {
    id: "coolidge", name: "Coolidge", sub: "Arizona · pop. ~19,700", z: "coolidge-az", r: "Coolidge_AZ",
    stage: "early", priceLabel: "$277k", delta: "−4.0% this year", verified: true,
    hook: "Grew 46% in four years and almost nobody outside Pinal County can find it on a map.",
    never: "A farm town stranded halfway between Phoenix and Tucson — the kind of place you drive through on the way to somewhere with an airport.",
    history: "Named for the president who dedicated the dam that made the valley farmable. It has been waiting for Phoenix to reach it ever since.",
    why: [
      "Population jumped from 13,433 to 19,674 between 2020 and 2024",
      "One of the last genuinely cheap footholds in the Phoenix orbit",
      "Prices are down 4% — you'd be buying growth on sale",
    ],
    jobs: "Pinal County's industrial corridor: manufacturing, logistics, and the spillover from Phoenix's semiconductor build-out.",
    get: "A house for $277k in a metro where the median is far north of that.",
    cost: "Heat and wildfire will both show up in your premium.",
    watch: [
      "The heat is the whole problem — days over 113°F are projected to rise 157% over thirty years",
      "Major wildfire risk",
    ],
    sources: ["Redfin", "Census", "First Street"],
  },
  {
    id: "johnsoncity", name: "Johnson City", sub: "Tennessee · pop. ~72,000", z: "johnson-city-tn", r: "Johnson-City_TN",
    stage: "heating", priceLabel: "$339k", delta: "+9.7% this year", verified: true,
    hook: "Quietly became one of the most-searched places in America to move to.",
    never: "It's in the far northeast corner of Tennessee, closer to Asheville than Nashville. The Tri-Cities have never had a marketing budget.",
    history: "A railroad junction that grew into the medical and university hub of upper east Tennessee, wedged into the Appalachian foothills.",
    why: [
      "Ranked the country's most popular relocation destination by MoveBuddha",
      "Cost of living still under the national average; median sale price 20% below it",
      "Projected to approach 80,000 people by 2030",
    ],
    jobs: "East Tennessee State University and Ballad Health carry the town. Thin outside education and healthcare.",
    get: "Appalachian foothills, a real university town, and a mortgage 20% under the national median.",
    cost: "Tennessee has no state income tax. That's part of the draw.",
    watch: [
      "Prices are up 9.7% in a year — the discount is closing while you read this",
      "One-industry risk if you're not in health or higher ed",
    ],
    sources: ["Redfin", "Zillow", "MoveBuddha"],
  },
  {
    id: "wildwood", name: "Wildwood", sub: "Florida · pop. ~36,500", z: "wildwood-fl", r: "Wildwood_FL",
    stage: "heating", priceLabel: "$366k", delta: "+8.6% this year", verified: true,
    hook: "The fastest-growing town in the United States. Its population doubled in three years.",
    never: "A crossroads town in Sumter County most Floridians know only as an exit sign — and as the edge of The Villages.",
    history: "A rail junction that spent a century as farmland, then found itself in the path of America's largest retirement development.",
    why: [
      "Doubled to 36,493 people in three years, with a 20% net migration rate",
      "The Villages is expanding straight through it, and infrastructure is following",
      "About an hour to Disney, an hour to the Gulf",
    ],
    jobs: "Healthcare, retail and construction — almost all of it serving the retirement boom next door.",
    get: "A new build at $366k in the fastest-growing town in the country.",
    cost: "Florida insurance rules apply. Get the quote on the address.",
    watch: [
      "Doubling a town in three years strains everything: roads, schools, doctors",
      "You'd be living inside someone else's retirement development",
      "Up 8.6% — the cheap window is closing",
    ],
    sources: ["Redfin", "U.S. News"],
  },
  {
    id: "tontitown", name: "Tontitown", sub: "Arkansas · pop. ~7,900", z: "tontitown-ar", r: "Tontitown_AR",
    stage: "late", priceLabel: "$450k", delta: "Priciest market in Arkansas", verified: true,
    hook: "An Italian-American farming village in the Ozarks that grew 70% in four years.",
    never: "Founded in 1898 by Italian immigrants who walked away from a failed Delta plantation. It has a grape festival and, until recently, nothing else.",
    history: "Grapes, then vineyards, then Walmart. Northwest Arkansas grew around it and swallowed it whole.",
    why: [
      "Population went from 4,685 to 7,941 between 2020 and 2024",
      "Northwest Arkansas is one of the strongest job markets in the country",
      "Ozark setting with real infrastructure in Fayetteville and Springdale next door",
    ],
    jobs: "The Northwest Arkansas triangle: Walmart HQ, Tyson Foods, J.B. Hunt, and the supplier ecosystem around them.",
    get: "Not much for $400k anymore. The median is $450k — the ceiling in Arkansas.",
    cost: "6.5% sales tax, and severe-weather exposure.",
    watch: [
      "You've missed the cheap years. This is now the most expensive housing in the state",
      "Severe storms are a real and regular feature",
    ],
    sources: ["Redfin", "Census", "Niche"],
  },
  {
    id: "hoschton", name: "Hoschton", sub: "Georgia · pop. ~4,000", z: "hoschton-ga", r: "Hoschton_GA",
    stage: "late", priceLabel: "$535k", delta: "+26.6% in one year", verified: true,
    hook: "The cautionary tale. A village of 2,758 that the Atlanta boom found.",
    never: "A one-street rail town between Atlanta and Athens that nobody outside Jackson County had heard of five years ago.",
    history: "Named for two brothers who ran the general store. For a century that was the whole story.",
    why: [
      "Still village-scaled and quiet, for now",
      "The growth is real, and it isn't stopping",
    ],
    jobs: "Almost none locally. It's a long commute to Atlanta, and that's the deal.",
    get: "Priced out. A $535k median, up 26.6% in twelve months.",
    cost: "The commute is the cost. Everything else follows from it.",
    watch: [
      "This is what 'too late' looks like — 26.6% in a single year",
      "Homes still take 208 days to sell, so that rise isn't demand, it's just cost",
      "The rural feel is being paved over as you watch",
    ],
    sources: ["Redfin", "Census"],
  },
];
